// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "defaultMode": string;
      "autoOpenPaneOnPdfOpen": boolean;
      "saveDocumentSessions": boolean;
      "responseLanguage": string;
      "geminiExecutablePath": string;
      "geminiDefaultModel": string;
      "geminiAllowedModels": string;
      "codexExecutablePath": string;
      "codexDefaultModel": string;
      "codexReasoningEffort": string;
      "codexAllowedModels": string;
      "codexEnableWebSearch": boolean;
      "codexSandboxMode": string;
      "codexApprovalMode": string;
      "codexWorkspaceRoot": string;
      "codexAutoCleanWorkspace": boolean;
      "retrievalChunkSize": number;
      "retrievalOverlapSize": number;
      "retrievalTopK": number;
      "retrievalIncludeAbstract": boolean;
      "retrievalIncludeNearbyContext": boolean;
      "privacyStoreLocalHistory": boolean;
      "privacySavePromptsOnly": boolean;
      "privacySaveResponses": boolean;
      "privacyRedactLocalFilePaths": boolean;
    };
  }
}
